### ISSUE TITLE
Nosuchmethoderror

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#402] opened 2019-07-31 22:06 UTC
![Screenshot_2019-08-01-00-04-11-795_com keyboardcrumbs haclient](https://user-images.githubusercontent.com/43727396/62251503-3ee18200-b3f0-11e9-836c-5ce3d9080448.png)

**Comment by estevez-dev** [comment] 2019-08-01 07:24
Closing as duplicate of #401

**Closed** 2019-08-01 07:24 UTC
