### ISSUE TITLE
Auto generate token to connect with HA

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#191] opened 2018-11-15 09:16 UTC
Hi
good feature request will be implement auto generate TOKEN to connect with Home Assistant. Now we must put token manually. It is not comfortable. In project app andrid name ARIELA it is implemented... maybe in HA Client you can implement this ?

**Comment by estevez-dev** [comment] 2018-11-15 09:43
But before generating a token how do you authenticate in ARIELA? Do you use username and password or legacy API password?

**Comment by pepeEL** [comment] 2018-11-15 09:55
yes

**Comment by estevez-dev** [comment] 2019-03-21 12:09
Closing as duplicate of #338

**Closed by estevez-dev** 2019-03-21 12:09 UTC
