### ISSUE TITLE
No interaction

### ISSUE THREAD

**Issue by geurtzen** [estevez-dev/ha_client#343] opened 2019-03-22 20:06 UTC
Hello,

I can see my configuration but cannot interact with devices. Devices do not respond.

Looks great so far. 

Regards, Maurice

**Comment by estevez-dev** [comment] 2019-03-23 07:30
Ok, first of all I want to ask you to open the app, try to interact with several entities and then go to Menu -> Log, copy it with a button in higher-right corner and paste it here. Thanks.

**Comment by geurtzen** [comment] 2019-03-23 12:54
Here it is (devices did not respond):

0323 13:51:15 [Debug] :  <!!!> Creating new HomeAssistant instance
0323 13:51:15 [Debug] :  AppLifecycleState.inactive
0323 13:51:15 [Debug] :  AppLifecycleState.resumed
0323 13:51:19 [Debug] :  Use lovelace is true
0323 13:51:19 [Debug] :  Socket connecting...
0323 13:51:21 [Debug] :  [Sending] ==> auth request
0323 13:51:21 [Debug] :  [Sending] ==> {"id": 1, "type":
"subscribe_events", "event_type": "state_changed"}
0323 13:51:21 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
0323 13:51:21 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
0323 13:51:21 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
0323 13:51:21 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
0323 13:51:21 [Debug] :  [Sending] ==> {"id": 6, "type":
"auth/current_user"}
0323 13:51:21 [Debug] :  [Sending] ==> {"id": 7, "type": "get_panels"}
0323 13:51:21 [Debug] :  [Received] <== id:1, success
0323 13:51:21 [Debug] :  [Received] <== id:2, success
0323 13:51:21 [Debug] :  Parsing 11 Home Assistant entities
0323 13:51:21 [Debug] :  [Received] <== id:4, success
0323 13:51:21 [Debug] :  [Received] <== id:7, success
0323 13:51:21 [Debug] :  [Received] <== id:3, error
0323 13:51:21 [Debug] :  [Received] <== id:5, success
0323 13:51:21 [Debug] :  We actually don`t need the list of servcies for now
0323 13:51:21 [Debug] :  [Received] <== id:6, success
0323 13:51:21 [Debug] :  Creating group-based UI
0323 13:51:21 [Debug] :  Fetch complete successful
0323 13:51:21 [Debug] :  Views count changed (null->1). Creating new tabs
controller.
0323 13:51:30 [Debug] :  media_player.keuken turn_on
0323 13:51:31 [Debug] :  [Received] <== event.state_changed: sun.sun
0323 13:51:38 [Debug] :  media_player.keuken turn_on

Regards, Maurice

**Comment by estevez-dev** [comment] 2019-03-24 21:23
You are not using Lovelace UI? I need to see a screenshot of entities you are trying to interact with. Looks like something is not supported for states UI.
Actually I want to advised you to switch to Lovelace and all should work fine.

**Comment by geurtzen** [comment] 2019-03-25 12:26
I am using default hassio interface. I think is is lovelace:

I have only 2 entities at this time. A Sonoff Basic and an internet radio. They work properly through the webinterface:


Regards,
Maurice
Op 24-3-2019 22:23:08, Yegor Vialov <notifications@github.com> schreef:
You are not using Lovelace UI? I need to see a screenshot of entities you are trying to interact with. Looks like something is not supported for states UI.
Actually I want to advised you to switch to Lovelace and all should work fine.

**Comment by estevez-dev** [comment] 2019-03-25 12:46
Sonoff Basic is not working too? Could you please show me a screenshot of main app screen? Also try to interact with Sonoff Basic and copy logs once again. In previous log output I saw only media_player. Thanks a lot.

**Comment by geurtzen** [comment] 2019-03-25 14:37
I recorder the app. When i switch the Sonoff, it turns off again on the
screen. It does not register in the app's log at all. When i switch
manually (on switch or webinterface) , i can see the event in the app's log.

Regards, Maurice

0325 15:30:16 [Debug] :  <!!!> Creating new HomeAssistant instance
0325 15:30:16 [Debug] :  AppLifecycleState.inactive
0325 15:30:16 [Debug] :  AppLifecycleState.resumed
0325 15:30:20 [Debug] :  Use lovelace is true
0325 15:30:20 [Debug] :  Socket connecting...
0325 15:30:21 [Debug] :  [Sending] ==> auth request
0325 15:30:21 [Debug] :  [Sending] ==> {"id": 1, "type":
"subscribe_events", "event_type": "state_changed"}
0325 15:30:21 [Debug] :  [Sending] ==> {"id": 2, "type": "get_states"}
0325 15:30:21 [Debug] :  [Sending] ==> {"id": 3, "type": "lovelace/config"}
0325 15:30:21 [Debug] :  [Sending] ==> {"id": 4, "type": "get_config"}
0325 15:30:21 [Debug] :  [Sending] ==> {"id": 5, "type": "get_services"}
0325 15:30:21 [Debug] :  [Sending] ==> {"id": 6, "type":
"auth/current_user"}
0325 15:30:21 [Debug] :  [Sending] ==> {"id": 7, "type": "get_panels"}
0325 15:30:21 [Debug] :  [Received] <== id:1, success
0325 15:30:21 [Debug] :  [Received] <== id:2, success
0325 15:30:21 [Debug] :  Parsing 13 Home Assistant entities
0325 15:30:21 [Debug] :  [Received] <== id:4, success
0325 15:30:21 [Debug] :  [Received] <== id:7, success
0325 15:30:21 [Debug] :  [Received] <== id:3, success
0325 15:30:21 [Debug] :  [Received] <== id:5, success
0325 15:30:21 [Debug] :  We actually don`t need the list of servcies for now
0325 15:30:21 [Debug] :  [Received] <== id:6, success
0325 15:30:21 [Debug] :  Creating Lovelace UI
0325 15:30:21 [Debug] :  --Title: Home
0325 15:30:21 [Debug] :  --Views count: 1
0325 15:30:21 [Debug] :  ----view id: null
0325 15:30:21 [Debug] :  Fetch complete successful
0325 15:30:21 [Debug] :  Views count changed (null->1). Creating new tabs
controller.
0325 15:30:32 [Debug] :  [Received] <== event.state_changed: sun.sun
0325 15:30:36 [Debug] :  AppLifecycleState.inactive
0325 15:30:39 [Debug] :  AppLifecycleState.paused
0325 15:31:32 [Debug] :  [Received] <== event.state_changed: sun.sun
0325 15:32:18 [Debug] :  [Received] <== event.state_changed:
media_player.keuken
0325 15:32:32 [Debug] :  [Received] <== event.state_changed: sun.sun
0325 15:33:32 [Debug] :  [Received] <== event.state_changed: sun.sun
0325 15:33:42 [Debug] :  AppLifecycleState.inactive
0325 15:33:42 [Debug] :  AppLifecycleState.resumed

**Comment by estevez-dev** [comment] 2019-03-25 15:59
I can't see screenshots, if there is any. Please attach them directly on github, not by mail. Thanks.

**Comment by geurtzen** [comment] 2019-03-25 16:19
Github does not support .mp4. I hope you can see it this way.
[(https://www.dropbox.com/s/7it5rspq9h3k57y/20190325_153258_edited.mp4?dl=0)]

**Comment by estevez-dev** [comment] 2019-03-25 20:54
There is an error in the bottom of the screen "Check connection settings". I suppose this is the reason. Does your "port" field is empty in connection settings? If so, try to fill it with "8123"

**Comment by estevez-dev** [comment] 2019-03-25 22:23
I see where is the issue. It is fixed already and will be delivered in next version. Try to add port to connection settings. Should work fine then.

**Comment by geurtzen** [comment] 2019-03-26 08:09
That was the solution. I set to the port to 443 (because i forward external 443 to internal 8123) and it works.
Thank you very much for your help and ofcourse for the app. 

Regards,
Maurice

Met vriendelijke groet,
Maurice Geurtzen
Email: maurice@geurtzen.com [mailto:maurice@geurtzen.com] | Mobiel: +31 (0)6 372 00 402 [tel:0031637200402]
Op 25-3-2019 23:23:23, Yegor Vialov <notifications@github.com> schreef:
I see where is the issue. It is fixed already and will be delivered in next version. Try to add port to connection settings. Should work fine then.

**Comment by estevez-dev** [comment] 2019-03-26 08:12
Nice to hear it helped. I will close this issue for now as it is not reproducible in future releases. Thanks for help of resolving this.

**Closed by estevez-dev** 2019-03-26 08:12 UTC
Labels: bug, waiting for details
