### ISSUE TITLE
Device tracker works intermittently

### ISSUE THREAD

**Issue by juancuellar14** [estevez-dev/ha_client#500] opened 2019-11-09 22:01 UTC
So I been testing the device tracker with the android app and the minimum time setting is 15 minutes but sometimes it takes up to an hour or so to update the location. On the Android phone I disabled the battery saving settings

**Comment by estevez-dev** [comment] 2019-11-10 13:58
May be relates to #490

**Comment by estevez-dev** [comment] 2019-11-10 21:40
Closing ad duplicate of #490 
Please follow #490 for updates.

**Closed by estevez-dev** 2019-11-10 21:40 UTC
Labels: bug
