### ISSUE TITLE
Lovelace view maximum

### ISSUE THREAD

**Issue by klejejs** [estevez-dev/ha_client#288] opened 2019-02-03 11:51 UTC
Currently maximum of 5 views are supported. If selected next one, it opens, but does not show as active one.

**Comment by klejejs** [comment] 2019-02-03 15:35
I think this might be some kind of bug, because currently it is working fine, but at some point it wasn't. Maybe there was an error in my Lovelace configuration, and the app is working fine.

**Comment by Klagio** [comment] 2019-02-03 17:42
I have 10 views and has always worked. You may want to exclude some custom component, they may cause problems

**Comment by estevez-dev** [comment] 2019-02-04 14:39
@klejejs this can be #235 . Try to force close the app though Android Settings - Apps and start it again. If not worked, open log viewer in app, copy log with a Copy button in upper right corner and past it here. Thanks.

**Comment by klejejs** [comment] 2019-02-04 14:56
Can confirm, its is duplicate of #235.

**Comment by estevez-dev** [comment] 2019-02-04 15:56
Closing as duplicate of #235

**Closed by estevez-dev** 2019-02-04 15:56 UTC
Labels: bug
