### ISSUE TITLE
Notification not received if HA Client is not running

### ISSUE THREAD

**Issue by maurizioandreotti60** [estevez-dev/ha_client#542] opened 2020-04-24 09:32 UTC
**HA Client version:** [Main menu -> About HA Client]
0.8.4
**Home Assistant version:**
0.108.8
**Device name:**
Xiaomi MI9T Pro
**Android version:**
10
**Description**
With the latest release of the HA Client the push notification are not received if the App is not open.  
In the past this was not necessary, so now I'm missing notifications.
Of course I have removed the integration and recreated as per indication of the latest release of the client.
The same issue occurs with a tablet and the smartphone of my wife.
During my test I received a message from Android saying the the app continues to close with an error and provide a log of the error.
Below you have the screen shot.

**Screenshots**
![image](https://user-images.githubusercontent.com/27202392/80197480-fc677180-861e-11ea-991f-93f4ec261184.png)

**Comment by estevez-dev** [comment] 2020-04-24 20:49
Duplicate of #538

**Closed by estevez-dev** 2020-04-24 20:49 UTC

**Comment by estevez-dev** [comment] 2020-04-28 22:09
Fixed in 0.8.5
