### ISSUE TITLE
nit, group/room aggregate on/off

### ISSUE THREAD

**Issue by adamf663** [estevez-dev/ha_client#411] opened 2019-08-21 15:14 UTC
I have my home automation organized around groups, such as kitchen, living room, bedroom, etc.
The web UI has an aggregated power switch for each group/room.
HA Client is missing this feature.

**Comment by estevez-dev** [comment] 2019-08-21 15:15
Duplicate of #365

**Closed by estevez-dev** 2019-08-21 15:15 UTC
