### ISSUE TITLE
Support for multiple HA servers

### ISSUE THREAD

**Issue by paulvsl** [estevez-dev/ha_client#532] opened 2020-04-10 15:31 UTC
Currently it is only possible to get access to one HA server from the app without reconfiguring the server details. 

Suggested enhancement: make access to more hosts available. So one can configure access to more HA servers and choose from a choice list which instance to be accessed by the app

Background is you have more than one location where you run HA for automation, and you want to be able to control all from within this app, by switching between servers. 

Kind regards 
Paul

**Comment by estevez-dev** [comment] 2020-05-29 09:29
Closing as duplicate of #390

**Closed by estevez-dev** 2020-05-29 09:29 UTC
Labels: feature/improvement
