### ISSUE TITLE
SSL issue on Android HA Client

### ISSUE THREAD

**Issue by buragohf** [estevez-dev/ha_client#519] opened 2019-12-19 14:47 UTC
Hello, 
i try to connect my Android HA Client to home-assistant with https connections but i get the following error in the log
########
.WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:352))
######
My certificates have been generated Using docker letsencrypt /Linux server container.
######
For xxxx.duckdns.org 
Let's encrypt authority X3
TLS1. 3
Aes_256_GCM
Méthode X25519
######

I'm able to connect in https to home assistant Using Chrome or Firefox from my Android device but not from the App. 
I'm looking for some help because i dont understand Why it's not working.
Best regards and thanks in advance for thé rime spent on this issue.

**Comment by estevez-dev** [comment] 2019-12-23 09:28
Hi. You are not alone. There is a lot of issues with SSL certificates in Flutter framework. Unfortunately it is not resolved yet.

**Comment by buragohf** [comment] 2019-12-25 02:00
Thank hou for your feedback ans Perry Christmas

**Comment by estevez-dev** [comment] 2020-05-29 09:10
Closing as duplicate of #180

**Closed by estevez-dev** 2020-05-29 09:10 UTC
Labels: bug
