### ISSUE TITLE
Problen with logging in [RapidSSL cert issue]

### ISSUE THREAD

**Issue by klaasnicolaas** [estevez-dev/ha_client#181] opened 2018-10-03 16:02 UTC
```
[Debug] :  AppLifecycleState.inactive
[Debug] :  AppLifecycleState.resumed
[Debug] :  Socket connecting...
[Global error] :  WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:363))
[Error] :  Socket connection timeout
```

**Comment by estevez-dev** [comment] 2020-05-29 09:11
Closing as duplicate of #180

**Closed by estevez-dev** 2020-05-29 09:11 UTC
Labels: bug, external blocker
