### ISSUE TITLE
GPS - old location

### ISSUE THREAD

**Issue by Jeroensum** [estevez-dev/ha_client#506] opened 2019-11-18 19:45 UTC
Hi,

I'vr been using the app for about a week now and since yesterday I've added geolocation. At the moment it's evening and I'm home, however the app still lists my location from this morning.

I've checked what Android thinks and Android puts me "at home". Google maps confirms this.

I have updated some entities and they show up in the interface so the connection to home assistant seems to work.

There are two possibilities that I think are relevant but I have no way of checking.
One is that the app is at fault and doesn't push the gps data. The other is that Home Assistant is at fault and doesn't process the gps data.

Can you please help me on how to check this and to file a proper bug report with the proper party?

**Comment by estevez-dev** [comment] 2019-11-18 20:35
Closing as duplicate of #490

**Closed by estevez-dev** 2019-11-18 20:35 UTC
