### ISSUE TITLE
Bug in translation 

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#261] opened 2018-12-31 15:23 UTC
I found a bug in translation.... Show "Cler" but should show "Clear"
![screenshot_20181231-161625](https://user-images.githubusercontent.com/16692223/50562886-6ff1bb00-0d18-11e9-9007-726450a02427.jpg)

When you are planing implement multilanguage?

**Comment by estevez-dev** [comment] 2019-01-02 08:30
Closing as duplicate of #262

**Closed by estevez-dev** 2019-01-02 08:30 UTC
