### ISSUE TITLE
Clicking lovelace views has no effect

### ISSUE THREAD

**Issue by ajayjohn** [estevez-dev/ha_client#298] opened 2019-02-17 16:20 UTC
### Issue 1
In the last few versions of the app, lovelace views can only be changed by swiping left or right. Clicking on the View title/image has no effect.

### Issue 2
Further, though swiping between the views works, the view title/image highlighted is always the second one, irrespective of which view content is displayed. 

**Images**
How the correct view is displayed on the HA Web interface
![http://imgur.com/gallery/NoSltFl](url)

How this app is always stuck on the second view even though it is displaying the contents of a different view
![http://imgur.com/gallery/SYqwxt1](url)

This doesn't happen all the time. I am unable to determine what causes the issue. So I hope to help this issue as a placeholder until the issue resurfaces and I can capture some useful logs.

**Comment by estevez-dev** [comment] 2019-02-17 16:40
I think it relates to #235 
Try to force close the app and launch it again. If it helps, we can close this as duplicate of #235

**Comment by estevez-dev** [comment] 2019-02-21 13:41
Resolved with #235

**Closed by estevez-dev** 2019-02-21 13:41 UTC
Labels: bug, waiting for details
