### ISSUE TITLE
Wiped Lovelace overview page

### ISSUE THREAD

**Issue by Morphy99** [estevez-dev/ha_client#518] opened 2019-12-16 13:21 UTC
**HA Client version:** 
1.20(42)
**Home Assistant version:**
0.102.3
**Device name:**
Samsung Galaxy S9
**Android version:**
9
**Description**
First time using this app and I added the device tracker badge for the mobile app to my Lovelace overview page but now the page is blank 😔 other tabs are unaffected.
Help.

**Comment by estevez-dev** [comment] 2019-12-16 17:05
So I tried to add a badge with device_tracker and it works fine for me:

![Screenshot_20191216-190140](https://user-images.githubusercontent.com/1819786/70926975-c265dd80-2036-11ea-9d4e-d3be31d27d56.png)

Could you please attach your Lovelace UI config here? You can find it tapping three-dots menu in upper right corner of web UI, selecting "Configure UI" then tapping the same three-dots menu again and selecting "Raw config editor". It will realyy help in solving this issue. Thanks.

**Comment by Morphy99** [comment] 2019-12-16 17:33
I forgot about that option! I thought I'd have to wait till I was home to
edit the file directly. Unfortunately on my phone I can't copy all but I
found the offending line under badges:

      - entity: {}

Or was it
     - {}

I copied before I deleted it but it copied something else, I'm guessing on
Android the copy in the raw config editor is a bit buggy.

**Comment by estevez-dev** [comment] 2019-12-16 17:48
So removing those line resolved the issue or not?

**Comment by Morphy99** [comment] 2019-12-16 18:49
Yep. I'll try adding another badge see if happens again in a bit.

**Comment by Morphy99** [comment] 2019-12-17 08:19
So I tried adding it again and again it added - {}. I also noticed adding a new entity on my lights panel didn't work so I don't think this is badge specific.

`title: Home
views:
  - badges:
      - entity: device_tracker.google_maps_
      - entity: sensor.disk_use_percent_home
      - entity: sensor.memory_free
      - entity: sensor.time_online
      - entity: sensor.cpu_temperature
      - entity: device_tracker.mobile
    cards:
      - entities:
          - light.fireplace_light
          - light.living_room_light
          - light.kitchen_light
        title: Lights
        type: entities
      - entities:
          - entity: switch.tv
          - entity: switch.hi_fi
          - entity: switch.meye01
          - entity: switch.ender3
          - entity: switch.sonoff_washing
        title: Plugs
        type: entities
      - entity: light.kitchen_light
        type: light
      - entity: light.living_room_light
        type: light
      - entity: light.fireplace_light
        type: light
      - entity: light.living_room_bookshelf_led_strip
        type: light
      - entity: light.hyperion
        type: light
      - cards:
          - entity: script.light_colour_cycle1
            hold_action:
              action: none
            icon: 'mdi:lighthouse-on'
            icon_height: 50px
            name: Colour Cycle Lights
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - entity: script.light_colour_cancel
            hold_action:
              action: none
            icon: 'mdi:lightbulb-on-outline'
            icon_height: 50px
            name: Reset Lights to White
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
        type: horizontal-stack
      - entities:
          - entity: scene.chill
          - entity: scene.party_mode
          - entity: scene.play_some_music
          - entity: scene.play_a_movie
          - entity: scene.watch_tv
        show_header_toggle: false
        title: Scenes
        type: entities
      - entity: script.docker_restart_hass
        hold_action:
          action: more-info
        icon: 'mdi:content-duplicate'
        icon_height: 50px
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        type: entity-button
      - card:
          entity: media_player.kodi_he
          type: media-control
        conditions:
          - entity: media_player.kodi_he
            state: playing
        type: conditional
      - card:
          entity: media_player.kodi_pi
          type: media-control
        conditions:
          - entity: media_player.kodi_pi
            state: playing
        type: conditional
      - card:
          entity: media_player.chromecast_audio_hi_fi
          type: media-control
        conditions:
          - entity: media_player.chromecast_audio_hi_fi
            state: playing
        type: conditional
      - card:
          entity: media_player.chromecast_main_tv
          type: media-control
        conditions:
          - entity: media_player.chromecast_main_tv
            state: playing
        type: conditional
      - card:
          entity: media_player.google_home_living_room_speaker
          type: media-control
        conditions:
          - entity: media_player.google_home_living_room_speaker
            state: playing
        type: conditional
      - entities:
          - entity: automation.home_alarm
            icon: 'mdi:alarm-light'
            name: Home Alarm Armed
          - entity: automation.home_presence
            icon: 'mdi:lightbulb-on'
            name: Switch on lights when home
          - entity: automation.home_non_presence
            icon: 'mdi:lightbulb-outline'
            name: Switch off lights when away
          - entity: binary_sensor.front_door_occupancy
        show_header_toggle: false
        title: Visitor Presence
        type: entities
      - detail: 2
        entity: sensor.front_door_temperature
        graph: line
        hours_to_show: 24
        type: sensor
      - entities:
          - entity: media_player.chromecast_audio_hi_fi
            icon: 'mdi:google-chrome'
          - entity: media_player.google_home_living_room_speaker
            icon: 'mdi:google-assistant'
          - entity: media_player.chromecast_main_tv
            icon: 'mdi:google-chrome'
          - entity: media_player.kodi_pi
            icon: 'mdi:kodi'
          - entity: media_player.kodi_he
            icon: 'mdi:kodi'
        show_header_toggle: false
        theme: Backend-selected
        title: Media Players
        type: entities
      - entities:
          - input_boolean.weekend_sunrise
          - sensor.weekend_alarm_time
          - input_number.weekend_alarm_hour
          - input_number.weekend_alarm_minutes
        type: entities
      - entities:
          - input_boolean.weekday_sunrise
          - sensor.weekday_alarm_time
          - input_number.weekday_alarm_hour
          - input_number.weekday_alarm_minutes
        type: entities
      - entities:
          - entity: sensor.sonoff_washing_energy_power
        hours_to_show: 1
        title: Washing Machine Power Usage
        type: history-graph
      - entities:
          - entity: input_select.state_washingmachine
        hours_to_show: 2
        title: Washing Machine History
        type: history-graph
      - entities:
          - entity: input_select.state_washingmachine
          - entity: sensor.sonoff_washing_energy_current
            icon: 'mdi:power-socket'
            name: Actual Current Usage
          - entity: sensor.sonoff_washing_energy_power
            icon: 'mdi:power-socket'
            name: Actual Power Usage
          - entity: sensor.sonoff_washing_energy_today
            icon: 'mdi:power-socket'
            name: Energy Used Today
          - entity: sensor.sonoff_washing_energy_yesterday
            icon: 'mdi:power-socket'
            name: Energy Used Yesterday
          - entity: sensor.sonoff_washing_energy_total
            icon: 'mdi:power-socket'
            name: Total Energy
          - entity: sensor.sonoff_washing_energy_totalstarttime
            icon: 'mdi:calendar'
            name: Total Energy Reset Date
        show_header_toggle: false
        title: Washing Machine
        type: entities
      - entity: light.led_djbox
        type: light
    path: default_view
    title: Overview
  - badges: []
    cards:
      - card:
          entity: camera.mjpeg_camera
          type: picture-entity
        conditions:
          - entity: switch.meye01
            state: 'on'
        type: conditional
    title: Living Room
  - badges: []
    cards: []
    title: Bedroom-Main
  - badges: []
    cards: []
    title: Kitchen
  - badges: []
    cards:
      - entities:
          - entity: media_player.chromecast_audio_hi_fi
            icon: 'mdi:google-chrome'
          - entity: media_player.google_home_living_room_speaker
            icon: 'mdi:google-assistant'
          - entity: media_player.chromecast_main_tv
            icon: 'mdi:google-chrome'
          - entity: media_player.kodi_pi
            icon: 'mdi:kodi'
          - entity: media_player.kodi_he
            icon: 'mdi:kodi'
        show_header_toggle: false
        theme: Backend-selected
        title: Media Players
        type: entities
    title: Entertainment
  - badges: []
    cards:
      - entities:
          - entity: sensor.front_door_temperature
          - entity: sensor.sensornode2_bme680_temperature
        hours_to_show: 72
        title: Home Temperature
        type: history-graph
      - entities:
          - sensor.sensornode2_bme680_humidity
        type: history-graph
      - entities:
          - entity: sensor.sensornode2_bme680_gas
        type: history-graph
      - entities:
          - entity: sensor.sensornode2_bme680_pressure
        type: history-graph
      - entities:
          - entity: sensor.sensornode2_bh1750_illuminance
        type: history-graph
    title: Climate
  - badges: []
    cards: []
    title: Security
  - badges: []
    cards:
      - entities:
          - entity: sensor.processor_use
        title: System CPU Usage
        type: history-graph
      - entities:
          - entity: sensor.cpu_temperature
        hours_to_show: 1
        title: System CPU Temperature
        type: history-graph
      - entities:
          - entity: sensor.memory_free
        title: System Free Memory
        type: history-graph
      - entities:
          - entity: sensor.network_throughput_in_eth0
        title: System Download Rate
        type: history-graph
      - entities:
          - entity: sensor.network_throughput_out_eth0
        title: System Upload Rate
        type: history-graph
      - entities:
          - entity: switch.docker_hass
            name: Docker Running
          - entity: script.docker_restart_hass
            icon: 'mdi:backup-restore'
          - type: divider
          - entity: sensor.ha_available_version
          - entity: sensor.ha_running_version
            icon: 'mdi:information-outline'
          - entity: sensor.hacs
          - type: divider
          - entity: sensor.docker_hass_cpu_use
          - entity: sensor.docker_hass_memory_use
          - entity: sensor.docker_hass_memory_use_percent
        show_header_toggle: false
        title: Home Assistant Docker
        type: entities
      - entities:
          - entity: binary_sensor.sonoff_update_available
          - entity: sensor.sonoff_firmware_version_available
          - entity: sensor.meye_sonoff_firmware
          - entity: sensor.ender3_sonoff_firmware
          - entity: sensor.washing_sonoff_firmware
          - entity: sensor.sensor01_sonoff_firmware
        show_header_toggle: false
        title: Sonoffs Firmware Version
        type: entities
      - cards:
          - entity: switch.docker_watchtower
            hold_action:
              action: toggle
            icon: 'mdi:content-duplicate'
            icon_height: 50px
            name: Update Docker Containers
            show_icon: true
            show_name: true
            tap_action:
              action: more-info
            type: entity-button
          - entity: script.update_sonoffs
            hold_action:
              action: toggle
            icon: 'mdi:content-duplicate'
            icon_height: 50px
            name: Update Sonoff Devices
            show_icon: true
            show_name: true
            tap_action:
              action: more-info
            type: entity-button
        type: horizontal-stack
      - card:
          entities:
            - entity: sensor.docker_watchtower_cpu_use
          type: history-graph
        conditions:
          - entity: switch.docker_watchtower
            state: 'on'
        type: conditional
      - card:
          entities:
            - entity: sensor.docker_watchtower_memory_use
          type: history-graph
        conditions:
          - entity: switch.docker_watchtower
            state: 'on'
        type: conditional
      - entities:
          - entity: switch.docker_nginx
            name: Docker Running
          - entity: script.docker_restart_nginx
            icon: 'mdi:backup-restore'
          - type: divider
          - entity: sensor.nginx_available_version
            icon: 'mdi:information-outline'
          - entity: sensor.docker_nginx_cpu_use
          - entity: sensor.docker_nginx_memory_use
          - entity: sensor.docker_nginx_memory_use_percent
        show_header_toggle: false
        title: NginX - Let's Encrypt Docker
        type: entities
      - entities:
          - entity: switch.docker_zigbee2mqtt
            name: Docker Running
          - entity: script.docker_restart_zigbee2mqtt
            icon: 'mdi:backup-restore'
          - type: divider
          - entity: sensor.zigbee2mqtt_available_version
            icon: 'mdi:information-outline'
          - entity: sensor.docker_zigbee2mqtt_cpu_use
          - entity: sensor.docker_zigbee2mqtt_memory_use
          - entity: sensor.docker_zigbee2mqtt_memory_use_percent
        show_header_toggle: false
        title: Zigbee2MQTT Docker
        type: entities
      - entities:
          - entity: switch.docker_mqtt
            name: Docker Running
          - entity: script.docker_restart_mqtt
            icon: 'mdi:backup-restore'
          - type: divider
          - entity: sensor.mosquitto_available_version
            icon: 'mdi:information-outline'
          - entity: sensor.docker_mqtt_cpu_use
          - entity: sensor.docker_mqtt_memory_use
          - entity: sensor.docker_mqtt_memory_use_percent
        show_header_toggle: false
        title: Mosquitto MQTT Docker
        type: entities
      - card:
          entity: script.ip_ban_clear
          hold_action:
            action: toggle
          icon: 'mdi:lock-reset'
          icon_height: 50px
          tap_action:
            action: more-info
          type: entity-button
        conditions:
          - entity: persistent_notification.ip_ban
            state: notifying
        type: conditional
      - cards:
          - content: |
              ## Add New Devices
              ---
            type: markdown
          - entity: switch.zigbee_discovery
            hold_action:
              action: none
            icon: 'mdi:power'
            icon_height: 50px
            name: Enable Zigbee Joining
            show_icon: true
            show_name: true
            tap_action:
              action: toggle
            type: entity-button
          - content: >
              ### Re-Sync Google Assistant Devices

              ---

              1. Say "Ok Google, sync home control devices"

              2. If not appearing still visit and try again:
              https://console.actions.google.com/u/0/project/hass-/simulator
            type: markdown
        type: vertical-stack
    icon: ''
    title: Server Admin
  - badges: []
    cards:
      - entity: sensor.ikea_dimmer_battery
        max: 100
        min: 0
        name: Dimmer Battery
        severity:
          green: 100
          red: 5
          yellow: 18
        theme: default
        type: gauge
      - entity: sensor.xiaomi_switch_battery
        max: 100
        min: 0
        name: Switch-Living Room Battery
        severity:
          green: 100
          red: 20
          yellow: 0
        theme: default
        type: gauge
    title: Battery Levels
  - badges: []
    cards:
      - entity: sensor.fireplace_linkquality
        max: 100
        min: 0
        name: Light-Fireplace Link Quality
        severity:
          green: 30
          red: 5
          yellow: 10
        theme: default
        type: gauge
        unit: '%'
      - entity: sensor.kitchen_linkquality
        max: 100
        min: 0
        name: Light-Kitchen Link Quality
        severity:
          green: 30
          red: 5
          yellow: 10
        theme: default
        type: gauge
        unit: '%'
      - entity: sensor.living_room_linkquality
        max: 100
        min: 0
        name: Light-Living Room Link Quality
        severity:
          green: 30
          red: 5
          yellow: 10
        theme: default
        type: gauge
        unit: '%'
      - entity: sensor.ikea_dimmer_linkquality
        max: 100
        min: 0
        name: Dimmer Link Quality
        severity:
          green: 0
          red: 0
          yellow: 0
        theme: default
        type: gauge
        unit: '%'
      - entity: sensor.xiaomi_switch_linkquality
        max: 100
        min: 0
        name: Switch-Living Room Link Quality
        severity:
          green: 0
          red: 0
          yellow: 0
        theme: default
        type: gauge
        unit: '%'
      - entity: sensor.0x000d6f000e056cfd_linkquality
        max: 100
        min: 0
        name: Sensor-Front Door Link Quality
        severity:
          green: 0
          red: 0
          yellow: 0
        theme: default
        type: gauge
        unit: '%'
      - entities:
          - entity: sensor.zigbee2mqtt_bridge_state
        type: entities
      - entity: sensor.meye01_status
        max: 100
        min: 0
        name: Switch-MEYE01 Link
        severity:
          green: 0
          red: 0
          yellow: 0
        theme: default
        type: gauge
        unit: '%'
      - entity: sensor.ender3_status
        max: 100
        min: 0
        name: Switch-Ender3 Link
        severity:
          green: 0
          red: 0
          yellow: 0
        theme: default
        type: gauge
        unit: '%'
    title: Wireless Levels
`

**Comment by estevez-dev** [comment] 2019-12-17 08:34
Thanks! This will really help.

**Comment by estevez-dev** [comment] 2020-05-29 09:16
Can't reproduce any more. Closing for now. Feel free to reopen if needed

**Closed by estevez-dev** 2020-05-29 09:16 UTC
Labels: bug
